# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_lock_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_data',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
