# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20171130_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='lock',
            name='state',
            field=models.CharField(default='unlocked', max_length=40),
        ),
    ]
