# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20171201_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='access_type',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
